apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./sources
  - ./apps

patches:
  - target:
      kind: HelmRelease
    patch: |-
      - op: add
        path: /spec/chart/spec/valuesFiles
        value:
          - ./values.yaml