
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app2
  namespace: app2
spec:
  interval: 5m
  releaseName: app2
  chart:
    spec:
      chart: app2
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: flux-system
  dependsOn: []
